package com.chornyi.microservices;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.chornyi.microservices.Application;
import org.junit.Test;
import static org.junit.Assert.*;

public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertTrue(true);
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
